import Head from 'next/head';

import Description from '../containers/Description/Description';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import Hero from '../containers/Hero/Hero';
import Show from '../containers/Show/Show';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Hero />
        <Description />
        <Show />
      </main>

      <Footer />
    </div>
  );
}
